<#
.SYNOPSIS
    Validates a workflow.md file generated by the design-workflow skill.

.DESCRIPTION
    Checks that:
    1. All Mermaid code blocks contain valid Mermaid flowchart syntax
    2. All JSON Schema code blocks contain valid JSON
    3. Required document sections are present
    4. Inter-phase contracts reference phases that exist in the document

.PARAMETER Path
    Path to the workflow.md file to validate.

.EXAMPLE
    pwsh -File Validate-Workflow.ps1 -Path "docs/workflows/my-workflow/workflow.md"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$Path
)

# --- Script-relative path resolution ---
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not (Test-Path "$root")) {
    Write-Error "Skill root directory not found at '$root'. If using a symlink, verify it points to a valid location."
    exit 1
}

# --- Helpers ---
$script:errors = @()
$script:warnings = @()

function Add-ValidationError {
    param([string]$Message)
    $script:errors += $Message
}

function Add-ValidationWarning {
    param([string]$Message)
    $script:warnings += $Message
}

# --- File existence check ---
if (-not (Test-Path $Path)) {
    Write-Error "File not found: $Path"
    exit 1
}

$content = Get-Content -Path $Path -Raw -Encoding UTF8
$lines = Get-Content -Path $Path -Encoding UTF8

# --- Section presence check ---
$requiredSections = @(
    "## Workflow Diagram",
    "## Stages & Phases",
    "## Inter-Phase Contracts"
)

foreach ($section in $requiredSections) {
    if ($content -notmatch [regex]::Escape($section)) {
        Add-ValidationError "Missing required section: '$section'"
    }
}

# Optional sections — warn if absent
$optionalSections = @(
    "## Assumptions & Open Questions"
)

foreach ($section in $optionalSections) {
    if ($content -notmatch [regex]::Escape($section)) {
        Add-ValidationWarning "Optional section not found: '$section'"
    }
}

# --- Extract and validate Mermaid blocks ---
$mermaidPattern = '(?ms)```mermaid\s*\r?\n(.*?)```'
$mermaidMatches = [regex]::Matches($content, $mermaidPattern)

if ($mermaidMatches.Count -eq 0) {
    Add-ValidationError "No Mermaid diagram found in the document"
} else {
    foreach ($match in $mermaidMatches) {
        $mermaidContent = $match.Groups[1].Value.Trim()

        # Check it starts with a valid Mermaid diagram type
        $validStarts = @("flowchart", "graph", "sequenceDiagram", "classDiagram", "stateDiagram", "erDiagram", "gantt", "pie", "gitGraph")
        $hasValidStart = $false
        foreach ($start in $validStarts) {
            if ($mermaidContent -match "^\s*$start") {
                $hasValidStart = $true
                break
            }
        }
        if (-not $hasValidStart) {
            Add-ValidationError "Mermaid block does not start with a valid diagram type. Found: '$($mermaidContent.Substring(0, [Math]::Min(50, $mermaidContent.Length)))...'"
        }

        # Check for balanced subgraph/end pairs
        $subgraphCount = ([regex]::Matches($mermaidContent, '\bsubgraph\b')).Count
        $endCount = ([regex]::Matches($mermaidContent, '\bend\b')).Count
        if ($subgraphCount -ne $endCount) {
            Add-ValidationError "Mermaid diagram has mismatched subgraph/end pairs: $subgraphCount subgraph(s) vs $endCount end(s)"
        }

        # Check for at least one edge (-->)
        if ($mermaidContent -notmatch '-->') {
            Add-ValidationWarning "Mermaid diagram has no edges (-->). Expected at least one connection between nodes."
        }
    }
}

# --- Extract and validate JSON blocks ---
$jsonPattern = '(?ms)```json\s*\r?\n(.*?)```'
$jsonMatches = [regex]::Matches($content, $jsonPattern)

if ($jsonMatches.Count -eq 0) {
    Add-ValidationWarning "No JSON Schema blocks found in the document"
} else {
    $jsonBlockIndex = 0
    foreach ($match in $jsonMatches) {
        $jsonBlockIndex++
        $jsonContent = $match.Groups[1].Value.Trim()

        try {
            $null = $jsonContent | ConvertFrom-Json -ErrorAction Stop
        } catch {
            # Find approximate line number
            $upToMatch = $content.Substring(0, $match.Index)
            $lineNum = ($upToMatch -split "`n").Count
            Add-ValidationError "Invalid JSON in block #$jsonBlockIndex (near line $lineNum): $($_.Exception.Message)"
        }
    }
}

# --- Extract phase names and validate contract references ---
$phasePattern = '####\s+Phase\s+[\d.]+:\s+(.+)'
$phaseNames = @()
foreach ($line in $lines) {
    if ($line -match $phasePattern) {
        $phaseNames += $Matches[1].Trim()
    }
}

# Extract contract references (Producer -> Consumer)
$contractPattern = '###\s+Contract:\s+(.+?)\s*->\s*(.+)'
foreach ($line in $lines) {
    if ($line -match $contractPattern) {
        $producer = $Matches[1].Trim()
        $consumer = $Matches[2].Trim()

        if ($phaseNames.Count -gt 0) {
            if ($producer -notin $phaseNames) {
                Add-ValidationWarning "Contract references unknown producer phase: '$producer'"
            }
            if ($consumer -notin $phaseNames) {
                Add-ValidationWarning "Contract references unknown consumer phase: '$consumer'"
            }
        }
    }
}

# --- Report results ---
Write-Host ""
Write-Host "=== Workflow Validation Report ===" -ForegroundColor Cyan
Write-Host "File: $Path"
Write-Host ""

if ($script:errors.Count -eq 0 -and $script:warnings.Count -eq 0) {
    Write-Host "PASSED - No issues found." -ForegroundColor Green
    exit 0
}

if ($script:warnings.Count -gt 0) {
    Write-Host "WARNINGS ($($script:warnings.Count)):" -ForegroundColor Yellow
    foreach ($w in $script:warnings) {
        Write-Host "  [WARN] $w" -ForegroundColor Yellow
    }
    Write-Host ""
}

if ($script:errors.Count -gt 0) {
    Write-Host "ERRORS ($($script:errors.Count)):" -ForegroundColor Red
    foreach ($e in $script:errors) {
        Write-Host "  [ERROR] $e" -ForegroundColor Red
    }
    Write-Host ""
    Write-Host "FAILED - Fix the errors above and re-validate." -ForegroundColor Red
    exit 1
} else {
    Write-Host "PASSED with warnings." -ForegroundColor Yellow
    exit 0
}
